# Generated by Django 2.2.5 on 2019-10-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
